name: Change issue status reopen

on:
  issue_comment:
    types: [created]

env:
  GH_TOKEN: ${{ github.token }}
  ISSUE_NUMBER: 0
jobs:
  issue-status-reopen:
    runs-on: ubuntu-latest
    steps:
      - name: Getting issue number
        run: |
          echo "Getting information about a linked issue number..."

          pull_info=$(gh pr view ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --json headRefName)
          response_code=$?
          
          if [ "$response_code" -ne 0 ]; then
            echo "ERROR: Request failed with exit status ${response_code}!"
            exit 1
          fi

          linked_issue_name=$(echo "$pull_info" | jq -r '.headRefName')
          ISSUE_NUMBER=$(echo "$linked_issue_name" | awk 'match($0, /[0-9]+/) {print substr($0, RSTART, RLENGTH)}')
          
          echo " - Issue num: $ISSUE_NUMBER"
          
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Reopen the status of a linked issue
        run: |
          echo "Reopening the status of a linked issue..."
          
          if [ -z "$ISSUE_NUMBER" ] || [ "$ISSUE_NUMBER" -eq 0 ]; then
            echo "No linked issue number found or extracted."
            exit 1
          else
             if ! changing_status=$(gh issue reopen $ISSUE_NUMBER --repo ${{ github.repository }} 2>&1); then
                 echo "ERROR: Failed to reopen issue: $changing_status"
                 exit 1
             else
                 echo "Issue reopened successfully!"
             fi
          fi