name: Reopen Issue on Comment

on:
  issue_comment:
    types: [created]

jobs:
  reopen_issue:
    runs-on: ubuntu-latest
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    steps:
      - name: Reopen related issue
        run: gh issue reopen $ISSUE_NUMBER
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}