name: Reopen Issue on Comment 2

on:
  pull_request:
    types: [synchronize]

env:
  GH_TOKEN: ${{ github.token }}
  ISSUE_NUMBER: 0

jobs:
  get_headRefName:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get pull request headRefName
        id: pr_info
        run: |
          headRefName=$(gh pr view ${{ github.event.number }} --json headRefName --jq '.headRefName')
          echo "$headRefName"
          
          ISSUE_NUMBER=$(echo "$headRefName" | awk 'match($0, /[0-9]+/) {print substr($0, RSTART, RLENGTH)}')
          echo " - Linked issue number: $ISSUE_NUMBER"
          
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Reopen related issue
        run: |
          echo "Trying to reopen issue..."
          echo "Issue number: $ISSUE_NUMBER"
          
          close_issue=$(gh issue close $ISSUE_NUMBER --repo ${{ github.repository }})
          response_code=$?
          
          if [ "$response_code" -ne 0 ]; then
            echo "ERROR: Request failed with exit status ${response_code}!"
            exit 1
          fi

          reopen_issue=$(gh issue reopen $ISSUE_NUMBER --repo ${{ github.repository }})
          response_code=$?

          if [ "$response_code" -ne 0 ]; then
            echo "ERROR: Request failed with exit status ${response_code}!"
            exit 1
          fi