name: Reopen Issue on Comment 2

on:
  pull_request:
    types: [synchronize]

env:
  GH_TOKEN: ${{ github.token }}
  ISSUE_NUMBER: 0

jobs:
  get_headRefName:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get pull request headRefName
        id: pr_info
        run: |
          headRefName=$(gh pr view ${{ github.event.number }} --json headRefName --jq '.headRefName')
          echo "$headRefName"
          
          ISSUE_NUMBER=$(echo "$linked_issue_name" | awk 'match($0, /[0-9]+/) {print substr($0, RSTART, RLENGTH)}')
          echo " - Linked issue number: $ISSUE_NUMBER"
          
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV