name: Reopen Issue on Comment

on:
  pull_request:
    types: [synchronize]

env:
  GH_TOKEN: ${{ github.token }}
  PULL_NUMBER: 0
  ISSUE_NUMBER: 0

jobs:
  reopen_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Getting information about a pull request and related issue
        run: |
          echo "Getting information about a pull request and related issue..."
          
          PULL_NUMBER=$(echo "${{ github.event.pull_request.url }}" | awk -F'/' '{print $NF}')
          echo " - Pull request number: $PULL_NUMBER"
          
          repo_name="${{ github.repository }}"
          
          pull_info=$(gh pr view $PULL_REQUEST_NUMBER $repo_name --json number,headRefName)
          echo "pull_info: $pull_info"
          
          linked_issue_name=$(echo "$pull_info" | jq -r '.headRefName')
          echo "linked_issue_name: $linked_issue_name"

          ISSUE_NUMBER=$(echo "$linked_issue_name" | awk 'match($0, /[0-9]+/) {print substr($0, RSTART, RLENGTH)}')
          echo " - Linked issue number: $ISSUE_NUMBER"
          
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV
          echo "PULL_NUMBER=$PULL_NUMBER" >> $GITHUB_ENV

      - name: Reopen related issue
        run: |
          echo "Trying to reopen issue..."
          
          reopen_issue=$(gh issue reopen $ISSUE_NUMBER --repo ${{ github.repository }})
          response_code=$?

          if [ "$response_code" -ne 0 ]; then
            echo "ERROR: Request failed with exit status ${response_code}!"
            exit 1
          fi